### ISSUE TITLE
[Meta] Make Gradle builds faster

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/config#425]
This is a meta issue and a checklist with tasks to make our Gradle builds faster across all repositories.

- [ ] (Ironically) *Find a Gradle plugin that measures time required the whole build pass successfully.* We need to measure what we do.

- [ ] Analyze [The case for `mavenLocal()`](https://docs.gradle.org/current/userguide/declaring_repositories.html#sec:case-for-maven-local) and apply filtering for only `io.spine.*` artifacts when `mavenLocal()` is used.

- [ ] Find out what it costs to use Gradle Enterprise (@alexander-yevsyukov is already on it).

- [ ] Analyze what detekt does to run its build faster. What do don't do what they do?

- [ ] Find other projects of Gradle plugins, and see what they do about testing their plugins. What do we need to change the way we work?

**Comment by alexander-yevsyukov** [comment]
@armiol, @dmdashenkov, @yevhenii-nadtochii, FYI.

**Comment by alexander-yevsyukov** [comment]
[Gradle Doctor](https://runningcode.github.io/gradle-doctor/) helps in some of the things we need.
